* Changed error message on ERR.  Added status warning. * Added "set -e" and "trap ... ERR" to the emitEnvironmentBash script's output. * Improved a comment. * "timeit" checks the exit status of the routines that jconfigure   invokes.  Will exit rather than continuing.  Yaay. * Added 'timeit' call to jbuild.compile, breaking historical   compatibility with what was probably an oversight. * Output more comments into the generated programs. * Got rid of nonstandard "exit -1". * Redid a bit more indentation.

diff --git a/rvm/bin/jconfigure b/rvm/bin/jconfigure
--- a/rvm/bin/jconfigure
+++ b/rvm/bin/jconfigure
@@ -45,7 +45,7 @@ fi
 
 # Stop immediately if any programs we call return errors.
 #
-trap 'echo >&2 "$ME: some command we just ran (probably with a final argument of \"$_\") returned an error; aborting execution.  Please Fix this."' ERR
+trap 'echo >&2 "$ME: some command we just ran (probably with a final argument of \"$_\") exited with status $?; aborting execution.  Please Fix this."' ERR
 trap 'echo >&2 "$ME: We just exited due to an error."' EXIT
 set -e;
 
@@ -700,6 +700,7 @@ function emitEnvironmentBash () {
    # read the target environment file
    #
    echo '#!/bin/bash'
+   echo ''
    echo '# Set the enviroment.'
    echo ""
    echo "# This file is generated by jconfigure from the configuration file"
@@ -711,6 +712,9 @@ function emitEnvironmentBash () {
    echo "# This file was generated from the configuration file:"
    echo "#      $CURRENT_CONFIG_FILE"
 
+   echo "trap 'echo >&2 \"\$ME: A command I just ran (probably with a final argument of \"\$_\")
+  exited with status \$?.  Something is broken; I give up.\"' ERR"
+   echo "set -e"
    echo ""
    echo "export $BUILD_DIRECTORY_STR1=$RVM_BUILD"
    echo "export $ROOT_DIRECTORY_STR1=$RVM_ROOT"
@@ -878,7 +882,7 @@ function emitController () {
 	#!/bin/bash
 	# Run all phases of vm builder.
 	set -e
-	ME=${0##*/}
+	ME="${0##*/}"
 
 	# timeit() $1: The command to run
 	#	   $2: That command's arguments.
@@ -893,11 +897,22 @@ function emitController () {
 	    # format, and use TIMEFORMAT instead of SECONDS...
 	    # TIMEFORMAT="%3lR"
 	    # time "$@"		
-	    # ...Or we can just deal.with integer seconds:
+	    # ...Or we can just deal.with integer seconds.  Since the SECONDS
+	    # variable is cumulative, it is compatible with the way we used to
+	    # do this.
+
+	    # Disable exit-on-error; inside "timeit", we can get a better
+	    # exit message than the default one.
+	    set +e
 	    "$@"
+	    set -e
 	    local status=$?
 	    echo "$SECONDS s"
-	    return $status;	    
+	    if [ $status != 0 ]; then
+		echo >&2 "$ME: Trouble while running \"$*\" (exit status $status); aborting execution"
+		exit $status;
+	    fi
+	    return $status;	# will always return 0
 	}
 
 	while [[ $# != 0 ]]; do
@@ -946,7 +961,7 @@ EOF
 	fi
 
 	if [[ $RECOMPILE_FLAG = -recompile ]]; then
-	    ./jbuild.compile $TRACE_FLAG -clean
+	    timeit ./jbuild.compile $TRACE_FLAG -clean
 	fi
 
 EOF
@@ -1848,18 +1863,20 @@ EOF
    }
 
 # Emit script to generate vm booter.
-# Taken:    InterfaceDeclarations.h in bootImageRunner directory
-# Returned: booter in build directory
-#
 function emitBooterLinker () {
    echo '#! /bin/bash'
+   echo ""
    echo '# Generate vm booter.'
-
-   # Allow the build directory to be different in the host/boot image
-   # writing system, and on the target system.
+   echo ""
+   echo '# Taken:    InterfaceDeclarations.h in bootImageRunner directory'
+   echo '# Returned: booter in build directory'
+   echo ""
+   echo '# Allow the build directory to be different in the host/boot image'
+   echo '# writing system, and on the target system.'
    echo ""
    echo 'ME="${0##*/}"'
    echo 'ROOT_DIR="${0%/*}"'
+   echo '# I do not understand the point behind this code. --Steve Augart'
    echo 'if [[ "$ROOT_DIR" = "." ]]; then'
    echo '   ROOT_DIR="$PWD"'
    echo 'fi'
@@ -1867,13 +1884,12 @@ function emitBooterLinker () {
    echo '   if [[ -f "$CURRENT_DIR"/"$ROOT_DIR"/"$ME" ]]; then'
    echo '      ROOT_DIR=$CURRENT_DIR/$ROOT_DIR'
    echo '   fi'
-   echo 'fi'        
+   echo 'fi'
    echo ""
    echo '. $ROOT_DIR/environment'
    echo ""
    echo "$BUILD_DIRECTORY_STR1=\$ROOT_DIR"
    echo ""
-
 
    echo 'SILENT_MAKE=--silent'
    echo 'if [[ $1 = -trace ]]; then'
@@ -2177,8 +2193,8 @@ function emitToolCompiler () {
 function emitToolPreprocessor () {
    echo '#! /bin/bash'
    echo '# Generate class files for vm tools that are not part of the build.'
-   echo '. $RVM_BUILD/environment'
    echo 'set -e'
+   echo '. $RVM_BUILD/environment'
    echo 'ME=${0##*/)'
 
    echo 'if [[ $# = 0 ]]; then'
@@ -2207,13 +2223,13 @@ function emitPluginBuilder () {
 	    echo "must specify Eclipse home: either
 	    echo "  1: set it in ${RVM_TARGET_CONFIG}, or
 	    echo "  2: use jbuild.plugin <eclipse dir>"
-	  exit -1
+	  exit 2
 	fi
 
 	# must have Ant
 	if [[ x${ANT_CMD} = x ]]; then
 	    echo "must specify ANT_CMD in ${RVM_TARGET_CONFIG}"
-	    exit -1
+	    exit 2
 	fi
 
 	# build the plugin
@@ -2240,19 +2256,19 @@ checkConfigurationOptions
 # Make a fresh start.
 #
 if [[ -e ${BUILD_DIRECTORY} ]]; then # old directory exists
-   if [ -t 0 ]; then # keyboard is live (ie. this is not an automated build)
-      echo -n "${ME}: ${BUILD_DIRECTORY} already exists, replace it? (y/n)"
-      read response
-      if [[ ${response} != y && ${response} != 'yes' ]]; then
-         echo "${ME}: operation aborted, nothing written"
-         trap '' EXIT
-	 ## Why on earth do we want to keep Make happy in this situation?
-	 ## Do we not want it to get upset?
-	 
-         exit 1 # to keep make happy
-      fi
-   fi
-   ( cd ${BUILD_DIRECTORY} && rm -rf * )
+    if [ -t 0 ]; then # keyboard is live (ie. this is not an automated build)
+	echo -n "${ME}: ${BUILD_DIRECTORY} already exists, replace it? (y/n)"
+	read response
+	if [[ ${response} != y && ${response} != 'yes' ]]; then
+	    echo "${ME}: operation aborted, nothing written"
+	    trap '' EXIT
+	    ## Why on earth do we want to keep Make happy in this situation?
+	    ## Do we not want it to get upset?
+
+	    exit 1 # to keep make happy
+	fi
+    fi
+    ( cd ${BUILD_DIRECTORY} && rm -rf * )
 fi
 
 # Create output directory structure.
@@ -2339,13 +2355,13 @@ chmod -x${PERM} ${BUILD_DIRECTORY}/security/JikesRVM.security
 echo "(control files and scripts installed) "
 
 if [[ ${quiet} != 1 ]]; then
-  if [ -t 0 ]; then # keyboard is live (ie. this is not an automated build)
-    echo "${ME}: ${CONFIGURATION_NAME} configuration is ready"
-    echo "${ME}: To build it, type:"
-    echo "${ME}:    cd ${BUILD_DIRECTORY}"
-    echo "${ME}:    ./jbuild"
-    echo "${ME}: To execute it (from any directory) type:"
-    echo "${ME}:    rvm <vm-args> classname <application-args>"
-  fi
+    if [ -t 0 ]; then # keyboard is live (ie. this is not an automated build)
+	echo "${ME}: ${CONFIGURATION_NAME} configuration is ready"
+	echo "${ME}: To build it, type:"
+	echo "${ME}:    cd ${BUILD_DIRECTORY}"
+	echo "${ME}:    ./jbuild"
+	echo "${ME}: To execute it (from any directory) type:"
+	echo "${ME}:    rvm <vm-args> classname <application-args>"
+    fi
 fi
 trap '' EXIT
